# Generated by Django 2.0 on 2019-07-09 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('emailid', models.CharField(max_length=200)),
                ('feedback', models.CharField(max_length=200)),
            ],
        ),
    ]
